#!/usr/bin/python

"""
Script to add constant values to a HXL dataset.
David Megginson
January 2015

Usage:

  hxladd -v country=Kenya < DATA_IN.csv > DATA_OUT.csv

(Use -h option to get all options.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
from hxl.filters.add import run

if __name__ == '__main__':
    run(sys.argv[1:], sys.stdin, sys.stdout)

# end
