#!/usr/bin/python
"""
Run hxl.filters.add from the command line.
David Megginson
Started January 2015
"""

from hxl.filters import run_script
import hxl.filters.add

if __name__ == '__main__':
    run_script(hxl.filters.add.run)
