#!/usr/bin/python

import sys
import argparse
from hxl.commands import parse_tags
from hxl.commands.hxlbounds import hxlbounds

# Command-line arguments
parser = argparse.ArgumentParser(description = 'Normalize a HXL file.')
parser.add_argument('infile', help='HXL file to read (if omitted, use standard input).', nargs='?', type=argparse.FileType('r'), default=sys.stdin)
parser.add_argument('outfile', help='HXL file to write (if omitted, use standard output).', nargs='?', type=argparse.FileType('w'), default=sys.stdout)
parser.add_argument('-b', '--bounds', help='Preserve text header row above HXL hashtags', required=True, type=argparse.FileType('r'))
parser.add_argument('-c', '--tags', help='Comma-separated list of column tags to include in error reports', metavar='tag,tag...', type=parse_tags, default='loc,org,sector,adm1,adm2,adm3')
args = parser.parse_args()

data = json.load(args.bounds)
shapes = []
for d in data['features']:
    shapes.append(shape(d['geometry']))

    # Call the command function
    hxlbounds(args.infile, args.outfile, shapes, tags=args.tags)


