#!/usr/bin/python

"""
Script to cut columns from a HXL dataset.
David Megginson
October 2014

Can use a whitelist of HXL tags, a blacklist, or both.

Usage:

  hxlcut -c org,country,sector < DATA_IN.csv > DATA_OUT.csv

(Use -h option to get all options.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
from hxl.filters.cut import run

if __name__ == '__main__':
    run(sys.argv[1:], sys.stdin, sys.stdout)

# end
