#!/usr/bin/python

"""
Script to count distinct values in a HXL dataset.
David Megginson
October 2014

Counts all combinations of the tags specified on the command line. In
the command-line version, you may omit the initial '#' from tag names
to avoid the need to quote them.

Only the *first* column with each hashtag is currently used.

Usage:

  hxlcount --tags tag1,tag2... < DATA_IN.csv > DATA_OUT.csv

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
import argparse
from hxl.commands import parse_tags

# Command-line arguments
parser = argparse.ArgumentParser(description = 'Generate aggregate counts for a HXL dataset')
parser.add_argument(
    'infile',
    help='HXL file to read (if omitted, use standard input).',
    nargs='?',
    type=argparse.FileType('r'),
    default=sys.stdin
    )
parser.add_argument(
    'outfile',
    help='HXL file to write (if omitted, use standard output).',
    nargs='?',
    type=argparse.FileType('w'),
    default=sys.stdout
    )
parser.add_argument(
    '-t',
    '--tags',
    help='Comma-separated list of column tags to include in error reports',
    metavar='tag,tag...',
    type=parse_tags,
    default='loc,org,sector,adm1,adm2,adm3'
    )
args = parser.parse_args()

hxlcount(args.input, args.output, args.tags)

#end
