#!/usr/bin/python

"""
Script to merge multiple HXL datasets
David Megginson
November 2014

Usage:

  hxlcut --tags org,country,sector DATASET01.csv DATASET02.csv > DATA_OUT.csv

(Use -h option to get all options.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
import argparse
from hxl.filters import parse_tags
from hxl.filters.hxlmerge import hxlmerge

# Command-line arguments
parser = argparse.ArgumentParser(description = 'Merge multiple HXL datasets')
parser.add_argument(
    'infile',
    help='HXL files to read.',
    nargs='+',
    type=argparse.FileType('r')
    )
parser.add_argument(
    '-o',
    '--outfile',
    help='HXL file to write (if omitted, use standard output).',
    metavar='filename',
    type=argparse.FileType('w'),
    default=sys.stdout
    )
parser.add_argument(
    '-t',
    '--tags',
    help='Comma-separated list of column tags to include',
    metavar='tag,tag...',
    type=parse_tags
    )
args = parser.parse_args()

# Call the command function
hxlmerge(args.infile, args.outfile, tags=args.tags)

# end
