#!/usr/bin/python

"""
Script to merge multiple HXL datasets
David Megginson
November 2014

Usage:

  hxlmerge --tags org,country,sector DATASET01.csv DATASET02.csv > DATA_OUT.csv

(Use -h option to get all options.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
from hxl.filters.hxlmerge import run

if __name__ == '__main__':
    run(sys.argv[1:], sys.stdin, sys.stdout)

# end
