#!/usr/bin/python
"""
Run hxl.filters.norm from the command line.
David Megginson
Started October 2014
"""

from hxl.filters import run_script
import hxl.filters.norm

if __name__ == '__main__':
    run_script(hxl.filters.norm.run)
