#!/usr/bin/python

"""
Script to normalise a HXL dataset.
David Megginson
October 2014

Expand all compact-disaggregated columns.
Strip columns without hashtags.
Strip leading and trailing whitespace from values.
Strip all but one pre-tag header row.

Usage:

  hxlnorm < DATA_IN.csv > DATA_OUT.csv

(Use -h option to get full usage.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
import argparse
from hxl.commands.hxlnorm import hxlnorm

# Command-line arguments
parser = argparse.ArgumentParser(description = 'Normalize a HXL file.')
parser.add_argument(
    'infile',
    help='HXL file to read (if omitted, use standard input).',
    nargs='?',
    type=argparse.FileType('r'),
    default=sys.stdin
    )
parser.add_argument(
    'outfile',
    help='HXL file to write (if omitted, use standard output).',
    nargs='?',
    type=argparse.FileType('w'),
    default=sys.stdout
    )
parser.add_argument(
    '-H',
    '--headers',
    help='Preserve text header row above HXL hashtags',
    action='store_const',
    const=True,
    default=False
    )
args = parser.parse_args()

# Call the command function
hxlnorm(args.infile, args.outfile, show_headers=args.headers)

# end
