#!/usr/bin/python

"""
Script to normalise a HXL dataset.
David Megginson
October 2014

Expand all compact-disaggregated columns.
Strip columns without hashtags.
Strip leading and trailing whitespace from values.
Strip all but one pre-tag header row.

Usage:

  hxlnorm < DATA_IN.csv > DATA_OUT.csv

(Use -h option to get full usage.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
from hxl.filters.norm import run

if __name__ == '__main__':
    run(sys.argv[1:], sys.stdin, sys.stdout)

# end
