#!/usr/bin/python
"""
Run hxl.filters.rename from the command line.
David Megginson
Started December 2014
"""

from hxl.filters import run_script
import hxl.filters.rename

if __name__ == '__main__':
    run_script(hxl.filters.rename.run)
