#!/usr/bin/python
"""
Run hxl.filters.sort from the command line.
David Megginson
Started January 2015
"""

from hxl.filters import run_script
import hxl.filters.sort

if __name__ == '__main__':
    run_script(hxl.filters.sort.run)
