#!/usr/bin/python

"""
Script to schema-validate a HXL dataset.
David Megginson
November 2014

Can use a whitelist of HXL tags, a blacklist, or both.

Usage:

  # with the default HXL core schema
  hxlvalidate MYDATA.csv > error-list.txt

  # with a custom schema
  hxlvalidate --schema MYSCHEMA.csv MYDATA.csv > error-list.txt

(Use -h option to get all options.)

License: Public Domain
Documentation: http://hxlstandard.org
"""

import sys
from hxl.filters.hxlvalidate import run

if __name__ == '__main__':
    run(sys.argv[1:], sys.stdin, sys.stdout)

# end

