#!/usr/bin/python
"""
Run hxl.filters.validate from the command line.
David Megginson
Started November 2014
"""

from hxl.filters import run_script
import hxl.filters.validate

if __name__ == '__main__':
    run_script(hxl.filters.validate.run)
